export const ACTIONS = {
  // Auth Actions
  SET_ISLOGGEDIN: "SET_ISLOGGEDIN",
  SET_USER: "SET_USER",
  SET_LOCATION: "SET_LOCATION",
  SET_LOADER: "SET_LOADER",




    // APP FILTERS Actions
    SET_CATEGORY: "SET_CATEGORY",
    SET_KEYWORDS: "SET_KEYWORDS",
    SET_JOB_LOCATION: "SET_JOB_LOCATION",
    SET_SEARCH:"SET_SEARCH",
    SET_RANGE:"SET_RANGE",
    SET_TAGS:"SET_TAGS",
    SET_EMPLOYMENT:"SET_EMPLOYMENT",
    SET_POSTED_ON:"SET_POSTED_ON",
    SET_EXPERIENCE:"SET_EXPERIENCE",
    SET_STRICT_MODE:"SET_STRICT_MODE"
    
};
