export const Countries = [
    { id: "0", name: "Afghanistan" },
    { id: "1", name: "land Islands" },
    { id: "2", name: "Albania" },
    { id: "3", name: "Algeria" },
    { id: "4", name: "American Samoa" },
    { id: "5", name: "Andorra" },
    { id: "6", name: "Angola" },
    { id: "7", name: "Anguilla" },
    { id: "8", name: "Antarctica" },
    { id: "9", name: "Antigua and Barbuda" },
    { id: "10", name: "Argentina" },
    { id: "11", name: "Armenia" },
    { id: "12", name: "Aruba" },
    { id: "13", name: "Australia" },
    { id: "14", name: "Austria" },
    { id: "15", name: "Azerbaijan" },
    { id: "16", name: "Bahamas" },
    { id: "17", name: "Bahrain" },
    { id: "18", name: "Bangladesh" },
    { id: "19", name: "Barbados" },
    { id: "20", name: "Belarus" },
    { id: "21", name: "Belgium" },
    { id: "22", name: "Belize" },
    { id: "23", name: "Benin" },
    { id: "24", name: "Bermuda" },
    { id: "25", name: "Bhutan" },
    { id: "26", name: "Bolivia, Plurinational State of " },
    { id: "27", name: "Bosnia and Herzegovina" },
    { id: "28", name: "Botswana" },
    { id: "29", name: "Bouvet Island" },
    { id: "30", name: "Brazil" },
    { id: "31", name: "British Indian Ocean Territory" },
    { id: "32", name: "Brunei Darussalam" },
    { id: "33", name: "Bulgaria" },
    { id: "34", name: "Burkina Faso" },
    { id: "35", name: "Burundi" },
    { id: "36", name: "Cambodia" },
    { id: "37", name: "Cameroon" },
    { id: "38", name: "Canada" },
    { id: "39", name: "Cape Verde" },
    { id: "40", name: "Cayman Islands" },
    { id: "41", name: "Central African Republic" },
    { id: "42", name: "Chad" },
    { id: "43", name: "Chile" },
    { id: "44", name: "China" },
    { id: "45", name: "Christmas Island" },
    { id: "46", name: "Cocos (Keeling) Islands" },
    { id: "47", name: "Colombia" },
    { id: "48", name: "Comoros" },
    { id: "49", name: "Congo" },
    { id: "50", name: "Congo, the Democratic Republic of the" },
    { id: "51", name: "Cook Islands" },
    { id: "52", name: "Costa Rica" },
    { id: "53", name: "Cocirc;te d'Ivoire" },
    { id: "54", name: "Croatia" },
    { id: "55", name: "Cuba" },
    { id: "56", name: "Cyprus" },
    { id: "57", name: "Czech Republic" },
    { id: "58", name: "Denmark" },
    { id: "59", name: "Djibouti" },
    { id: "60", name: "Dominica" },
    { id: "61", name: "Dominican Republic" },
    { id: "62", name: "Ecuador" },
    { id: "63", name: "Egypt" },
    { id: "64", name: "El Salvador" },
    { id: "65", name: "Equatorial Guinea" },
    { id: "66", name: "Eritrea" },
    { id: "67", name: "Estonia" },
    { id: "68", name: "Ethiopia" },
    { id: "69", name: "Falkland Islands (Malvinas)" },
    { id: "70", name: "Faroe Islands" },
    { id: "71", name: "Fiji" },
    { id: "72", name: "Finland" },
    { id: "73", name: "France" },
    { id: "74", name: "French Guiana" },
    { id: "75", name: "French Polynesia" },
    { id: "76", name: "French Southern Territories" },
    { id: "77", name: "Gabon" },
    { id: "78", name: "Gambia" },
    { id: "79", name: "Georgia" },
    { id: "80", name: "Germany" },
    { id: "81", name: "Ghana" },
    { id: "82", name: "Gibraltar" },
    { id: "83", name: "Greece" },
    { id: "84", name: "Greenland" },
    { id: "85", name: "Grenada" },
    { id: "86", name: "Guadeloupe" },
    { id: "87", name: "Guam" },
    { id: "88", name: "Guatemala" },
    { id: "89", name: "Guernsey" },
    { id: "90", name: "Guinea" },
    { id: "91", name: "Guinea-Bissau" },
    { id: "92", name: "Guyana" },
    { id: "93", name: "Haiti" },
    { id: "94", name: "Heard Island and McDonald Islands" },
    { id: "95", name: "Holy See (Vatican City State)" },
    { id: "96", name: "Honduras" },
    { id: "97", name: "Hong Kong" },
    { id: "98", name: "Hungary" },
    { id: "99", name: "Iceland" },
    { id: "100", name: "India" },
    { id: "1.1", name: "Indonesia" },
    { id: "1.2", name: "Iran, Islamic Republic of" },
    { id: "1.3", name: "Iraq" },
    { id: "1.4", name: "Ireland" },
    { id: "1.5", name: "Isle of Man" },
    { id: "1.6", name: "Israel" },
    { id: "1.7", name: "Italy" },
    { id: "1.8", name: "Jamaica" },
    { id: "1.9", name: "Japan" },
    { id: "2.0", name: "Jersey" },
    { id: "2.1", name: "Jordan" },
    { id: "2.2", name: "Kazakhstan" },
    { id: "2.3", name: "Kenya" },
    { id: "2.4", name: "Kiribati" },
    { id: "2.5", name: "Korea, Democratic People's Republic of" },
    { id: "2.6", name: "Korea, Republic of" },
    { id: "2.7", name: "Kuwait" },
    { id: "2.8", name: "Kyrgyzstan" },
    { id: "2.9", name: "Lao  People's Democratic Republic" },
    { id: "3.0", name: "Latvia" },
    { id: "3.1", name: "Lebanon" },
    { id: "3.2", name: "Lesotho" },
    { id: "3.3", name: "Liberia" },
    { id: "3.4", name: "Libyan Arab Jamahiriya" },
    { id: "3.5", name: "Liechtenstein" },
    { id: "3.6", name: "Lithuania" },
    { id: "3.7", name: "Luxembourg" },
    { id: "3.8", name: "Macao" },
    { id: "3.9", name: "Macedonia, the former Yugoslav Republic of" },
    { id: "4.0", name: "Madagascar" },
    { id: "4.1", name: "Malawi" },
    { id: "4.2", name: "Malaysia" },
    { id: "4.3", name: "Maldives" },
    { id: "4.4", name: "Mali" },
    { id: "4.5", name: "Malta" },
    { id: "4.6", name: "Marshall Islands" },
    { id: "4.7", name: "Martinique" },
    { id: "4.8", name: "Mauritania" },
    { id: "4.9", name: "Mauritius" },
    { id: "5.0", name: "Mayotte" },
    { id: "5.1", name: "Mexico" },
    { id: "5.2", name: "Micronesia, Federated States of" },
    { id: "5.3", name: "Moldova, Republic of" },
    { id: "5.4", name: "Monaco" },
    { id: "5.5", name: "Mongolia" },
    { id: "5.6", name: "Montenegro" },
    { id: "5.7", name: "Montserrat" },
    { id: "5.8", name: "Morocco" },
    { id: "5.9", name: "Mozambique" },
    { id: "6.0", name: "Myanmar" },
    { id: "6.1", name: "Namibia" },
    { id: "6.2", name: "Nauru" },
    { id: "6.3", name: "Nepal" },
    { id: "6.4", name: "Netherlands" },
    { id: "6.5", name: "Netherlands Antilles" },
    { id: "6.6", name: "New Caledonia" },
    { id: "6.7", name: "New Zealand" },
    { id: "6.8", name: "Nicaragua" },
    { id: "6.9", name: "Niger" },
    { id: "8.0", name: "Nigeria" },
    { id: "8.1", name: "Niue" },
    { id: "8.2", name: "Norfolk Island" },
    { id: "8.3", name: "Northern Mariana Islands" },
    { id: "8.4", name: "Norway" },
    { id: "8.5", name: "Oman" },
    { id: "8.6", name: "Pakistan" },
    { id: "8.7", name: "Palau" },
    { id: "8.8", name: "Palestinian Territory, Occupied" },
    { id: "8.9", name: "Panama" },
    { id: "9.0", name: "Papua New Guinea" },
    { id: "9.1", name: "Paraguay" },
    { id: "9.2", name: "Peru" },
    { id: "9.3", name: "Philippines" },
    { id: "9.4", name: "Pitcairn" },
    { id: "9.5", name: "Poland" },
    { id: "9.6", name: "Portugal" },
    { id: "9.7", name: "Puerto Rico" },
    { id: "9.8", name: "Qatar" },
    { id: "9.9", name: "Reacute;union" },
    { id: "1a", name: "Romania" },
    { id: "2a", name: "Russian Federation" },
    { id: "3a", name: "Rwanda" },
    { id: "4a", name: "Saint Barth&eacute;lemy" },
    { id: "5a", name: "Saint Helena, Ascension and Tristan da Cunha" },
    { id: "6a", name: "Saint Kitts and Nevis" },
    { id: "7a", name: "Saint Lucia" },
    { id: "8a", name: "Saint Martin (French part)" },
    { id: "9a", name: "Saint Pierre and Miquelon" },
    { id: "10a", name: "Saint Vincent and the Grenadines" },
    { id: "11a", name: "Samoa" },
    { id: "12a", name: "San Marino" },
    { id: "13a", name: "Sao Tome and Principe" },
    { id: "14a", name: "Saudi" },
    { id: "15a", name: "Senegal Arabia" },
    { id: "16a", name: "Serbia" },
    { id: "17a", name: "Seychelles" },
    { id: "18a", name: "Sierra Leone" },
    { id: "19a", name: "Singapore" },
    { id: "20a", name: "Slovakia" },
    { id: "21a", name: "Slovenia" },
    { id: "22a", name: "Solomon Islands" },
    { id: "23a", name: "Somalia" },
    { id: "24a", name: "South Africa" },
    { id: "25a", name: "South Georgia and the South Sandwich Islands" },
    { id: "26a", name: "Spain" },
    { id: "27a", name: "Sri Lanka" },
    { id: "28a", name: "Sudan" },
    { id: "29a", name: "Suriname" },
    { id: "30a", name: "Svalbard and Jan Mayen" },
    { id: "31a", name: "Swaziland" },
    { id: "32a", name: "Sweden" },
    { id: "33a", name: "Switzerland" },
    { id: "34a", name: "Syrian Arab Republic" },
    { id: "35a", name: "Taiwan, Province of China" },
    { id: "36a", name: "Tajikistan" },
    { id: "37a", name: "Tanzania, United Republic of" },
    { id: "38a", name: "Thailand" },
    { id: "39a", name: "Timor-Leste" },
    { id: "40a", name: "Togo" },
    { id: "41a", name: "Tokelau" },
    { id: "42a", name: "Tonga" },
    { id: "43a", name: "Trinidad and Tobago" },
    { id: "44a", name: "Tunisia" },
    { id: "45a", name: "Turkey" },
    { id: "46a", name: "Turkmenistan" },
    { id: "47a", name: "Turks and Caicos Islands" },
    { id: "48a", name: "Tuvalu" },
    { id: "49a", name: "Uganda" },
    { id: "50a", name: "Ukraine" },
    { id: "51a", name: "United Arab Emirates" },
    { id: "52a", name: "United Kingdom" },
    { id: "53a", name: "United States" },
    { id: "54a", name: "United States Minor Outlying Islands" },
    { id: "55a", name: "Uruguay" },
    { id: "56a", name: "Uzbekistan" },
    { id: "57a", name: "Vanuatu" },
    { id: "58a", name: "Venezuela, Bolivarian Republic of" },
    { id: "59a", name: "Viet Nam" },
    { id: "60a", name: "Virgin Islands, British" },
    { id: "61a", name: "Virgin Islands, U.S." },
    { id: "62a", name: "Wallis and Futuna" },
    { id: "63a", name: "Western Sahara" },
    { id: "64a", name: "Yemen" },
    { id: "65a", name: "Zambia" },
    { id: "66a", name: "Zimbabwe" }
  ];